config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # Category Pages Route
  root :to                                => "categories#index"
  get '/index.html'                       => redirect('/')
  get '/about-us.html'                    => redirect('/about-us')
  get '/about-us'                         => 'categories#about_us'
  get '/bathroom-accessories.html'        => redirect('/bathroom-accessories')
  get '/bathroom-accessories'             => 'categories#bathroom_accessories'
  get '/bathroom-fittings.html'           => redirect('/bathroom-fittings')
  get '/bathroom-fittings'                => 'categories#bathroom_fittings'
  get '/bathtubs.html'                    => redirect('/bathtubs')
  get '/bathtubs'                         => 'categories#bathtubs'
  get '/brass-valves-and-fittings.html'   => redirect('/brass-valves-and-fittings')
  get '/brass-valves-and-fittings'        => 'categories#brass_valves_and_fittings'
  get '/ci-manhole-covers.html'           => redirect('/ci-manhole-covers')
  get '/ci-manhole-covers'                => 'categories#ci_manhole_covers'
  get '/ci-pipes-and-fittings.html'       => redirect('/ci-pipes-and-fittings')
  get '/ci-pipes-and-fittings'            => 'categories#ci_pipes_and_fittings'
  get '/cpvc-pipes-and-fittings.html'     => redirect('/cpvc-pipes-and-fittings')
  get '/cpvc-pipes-and-fittings'          => 'categories#cpvc_pipes_and_fittings'
  get '/gi-pipes-and-fittings.html'       => redirect('/gi-pipes-and-fittings')
  get '/gi-pipes-and-fittings'            => 'categories#gi_pipes_and_fittings'
  get '/hand-dryer.html'                  => redirect('/hand-dryer')
  get '/hand-dryer'                       => 'categories#hand_dryer'
  get '/hdpe-pipes-and-fittings.html'     => redirect('/hdpe-pipes-and-fittings')
  get '/hdpe-pipes-and-fittings'          => 'categories#hdpe_pipes_and_fittings'
  get '/kitchen-sinks.html'               => redirect('/about-us')
  get '/kitchen-sinks'                    => 'categories#kitchen_sinks'
  get '/mirrors-and-cabinets.html'        => redirect('/mirrors-and-cabinets')
  get '/mirrors-and-cabinets'             => 'categories#mirrors_and_cabinets'
  get '/ppr-pipes-and-fittings.html'      => redirect('/ppr-pipes-and-fittings')
  get '/ppr-pipes-and-fittings'           => 'categories#ppr_pipes_and_fittings'
  get '/ptmt-fittings.html'               => redirect('/ptmt-fittings')
  get '/ptmt-fittings'                    => 'categories#ptmt_fittings'
  get '/pvc-pipes-and-fittings.html'      => redirect('/pvc-pipes-and-fittings')
  get '/pvc-pipes-and-fittings'           => 'categories#pvc_pipes_and_fittings'
  get '/sanitaryware.html'                => redirect('/sanitaryware')
  get '/sanitaryware'                     => 'categories#sanitaryware'
  get '/shower-enclosures.html'           => redirect('/shower-enclosures')
  get '/shower-enclosures'                => 'categories#shower_enclosures'
  get '/shower-panels.html'               => redirect('/shower-panels')
  get '/shower-panels'                    => 'categories#shower_panels'
  get '/steam-solutions.html'             => redirect('/steam-solutions')
  get '/steam-solutions'                  => 'categories#steam_solutions'
  get '/swr-pipes-and-fittings.html'      => redirect('/swr-pipes-and-fittings')
  get '/swr-pipes-and-fittings'           => 'categories#swr_pipes_and_fittings'
  get '/tiles.html'                       => redirect('/tiles')
  get '/tiles'                            => 'categories#tiles'
  get '/upvc-pipes-and-fittings.html'     => redirect('/upvc-pipes-and-fittings')
  get '/upvc-pipes-and-fittings'          => 'categories#upvc_pipes_and_fittings'
  get '/water-heater.html'                => redirect('/water-heater')
  get '/water-heater'                     => 'categories#water_heater'
  get '/water-tank.html'                  => redirect('/water-tank')
  get '/water-tank'                       => 'categories#water_tank'
  get '/contact.html'                     => redirect('/contact')
  post '/contact'                         => 'categories#contact'

  get '/login'                            => 'sessions#new', :as => 'login_path'
  post '/login'                           => 'sessions#create'
  delete '/logout'                        => 'sessions#destroy'

  # resources :users, :only =>[:new,:create,:index]
  get '/users/new'                        => 'users#new', :as => 'signup_path'
  post '/users/create'                    => 'users#create'
  get '/users'                            => 'users#index'
  get '/users/:id'                        => 'users#show', :as => 'user'

  get '/reports'                          => 'reports#index', :as => 'reports'
  get '/reports/new'                      => 'reports#new', :as => 'generate_report'
  post '/reports/create'                  => 'reports#create'
  get '/reports/show'                     => 'reports#show'
  get '/reports/:id'                      => 'reports#show', :as => 'report'
  delete '/reports/:id'                   => 'reports#destroy'
end

app/models/user.rb
class User < ApplicationRecord
	# attr_accessor :password
	EMAIL_REGEX = /\b[A-Z0-9._%a-z\-]+@(?:[A-Z0-9a-z\-]+\.)+[A-Za-z]{2,4}\z/
	validates :username, :presence => true, :uniqueness => true, :length => { :in => 3..20 }
	validates :email, :presence => true, :uniqueness => true, :format => EMAIL_REGEX
	validates :password, :confirmation => true #password_confirmation attr
	validates_length_of :password, :in => 6..20, :on => :create
	attr_accessor :password

	before_save :encrypt_password
	after_save :clear_password

	def encrypt_password
		if password.present?
			self.salt = BCrypt::Engine.generate_salt
			self.encrypted_password = BCrypt::Engine.hash_secret(password, salt)
		end
	end

	def authenticate password
		return self.encrypted_password == BCrypt::Engine.hash_secret(password,self.salt) ? true : false
	end
	def clear_password
		self.password = nil
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	require 'digest/sha1'
	before_filter :set_current_user, :only => [:index, :create, :show]

	def index
		if session[:user_id].present?
			@users = User.all
		else
			redirect_to login_path_url
		end
	end
	
	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			flash[:alert] = "You signed up successfully. Please give us sometime and our team shall grant the access to you."
			flash[:color]= "valid"
		else
			flash[:alert] = "Form is invalid"
			flash[:color]= "invalid"
		end
		render "new"
	end

	def show
		if session[:user_id].present?
			@user = User.find(params[:id])
		else
			redirect_to login_path_url
		end
	end

	private

	def user_params
		params.require(:user).permit(:username, :email, :password, :salt, :encrypted_password, :password_confirmation)
	end

	def set_current_user
		current_user
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<table>
	<caption>List of All User Who Signed Up</caption>
	<thead>
		<tr>
			<th>User Name</th>
			<th>User Email</th>
		</tr>
	</thead>
	<tbody>
		<% @users = User.all %>
		<% @users.each do |user| %>
			<tr>
				<td><%= user.username %></td>
				<td><%= user.email %></td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/users/new.html.erb
<% @page_title = "UserAuth | Signup" %>
<div class="Sign_Form">
  <h1>Sign Up</h1>
  <% if flash[:alert] %>
    <div id="alert">
       <%= flash[:alert] %> 
    </div>
  <% end %>
  <%= form_for(:user, :url => {:controller => 'users', :action => 'create'}) do |f| %>
    <p> Username:</br> <%= f.text_field :username%> </p>
    <p> Email:</br> <%= f.text_field :email%> </p>
    <p> Password:</br> <%= f.password_field :password%></p>
    <p> Password Confirmation:</br> <%= f.password_field :password_confirmation%> </p>
    <%= f.submit :Signup %>
  <% end %>
  <% if @user.errors.any? %>
    <ul class="Signup_Errors">
    <% for message_error in @user.errors.full_messages %>
      <li>* <%= message_error %></li>
    <% end %>
    </ul>
  <% end %>
</div>

app/views/users/show.html.erb
<% @page_title = "Welcome" + @user.username %>
<div class="User_Form">
  <h1>Welcome <%= @user.username %></h1>
  <% if flash[:alert] %>
    <div id="alert">
       <%= flash[:alert] %> 
    </div>
  <% end %>
  <div>
    These are the details we have about you! :)
  </div>
  <div>Name: <strong><%= @user.username %></strong></div>
  <div>Email: <strong><%= @user.email %></strong></div>
  <div>Access: <strong><%= @user.has_permit ? 'Granted :)' : 'Denied :(' %></strong></div>
  <p><%= link_to "Generate Report Now!", generate_report_url %></p>
  <p><%= link_to "Check Reports!", reports_url %></p>
</div>