config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # Category Pages Route
  root :to                                => "categories#index"
  get '/index.html'                       => redirect('/')
  get '/about-us.html'                    => redirect('/about-us')
  get '/about-us'                         => 'categories#about_us'
  get '/bathroom-accessories.html'        => redirect('/bathroom-accessories')
  get '/bathroom-accessories'             => 'categories#bathroom_accessories'
  get '/bathroom-fittings.html'           => redirect('/bathroom-fittings')
  get '/bathroom-fittings'                => 'categories#bathroom_fittings'
  get '/bathtubs.html'                    => redirect('/bathtubs')
  get '/bathtubs'                         => 'categories#bathtubs'
  get '/brass-valves-and-fittings.html'   => redirect('/brass-valves-and-fittings')
  get '/brass-valves-and-fittings'        => 'categories#brass_valves_and_fittings'
  get '/ci-manhole-covers.html'           => redirect('/ci-manhole-covers')
  get '/ci-manhole-covers'                => 'categories#ci_manhole_covers'
  get '/ci-pipes-and-fittings.html'       => redirect('/ci-pipes-and-fittings')
  get '/ci-pipes-and-fittings'            => 'categories#ci_pipes_and_fittings'
  get '/cpvc-pipes-and-fittings.html'     => redirect('/cpvc-pipes-and-fittings')
  get '/cpvc-pipes-and-fittings'          => 'categories#cpvc_pipes_and_fittings'
  get '/gi-pipes-and-fittings.html'       => redirect('/gi-pipes-and-fittings')
  get '/gi-pipes-and-fittings'            => 'categories#gi_pipes_and_fittings'
  get '/hand-dryer.html'                  => redirect('/hand-dryer')
  get '/hand-dryer'                       => 'categories#hand_dryer'
  get '/hdpe-pipes-and-fittings.html'     => redirect('/hdpe-pipes-and-fittings')
  get '/hdpe-pipes-and-fittings'          => 'categories#hdpe_pipes_and_fittings'
  get '/kitchen-sinks.html'               => redirect('/about-us')
  get '/kitchen-sinks'                    => 'categories#kitchen_sinks'
  get '/mirrors-and-cabinets.html'        => redirect('/mirrors-and-cabinets')
  get '/mirrors-and-cabinets'             => 'categories#mirrors_and_cabinets'
  get '/ppr-pipes-and-fittings.html'      => redirect('/ppr-pipes-and-fittings')
  get '/ppr-pipes-and-fittings'           => 'categories#ppr_pipes_and_fittings'
  get '/ptmt-fittings.html'               => redirect('/ptmt-fittings')
  get '/ptmt-fittings'                    => 'categories#ptmt_fittings'
  get '/pvc-pipes-and-fittings.html'      => redirect('/pvc-pipes-and-fittings')
  get '/pvc-pipes-and-fittings'           => 'categories#pvc_pipes_and_fittings'
  get '/sanitaryware.html'                => redirect('/sanitaryware')
  get '/sanitaryware'                     => 'categories#sanitaryware'
  get '/shower-enclosures.html'           => redirect('/shower-enclosures')
  get '/shower-enclosures'                => 'categories#shower_enclosures'
  get '/shower-panels.html'               => redirect('/shower-panels')
  get '/shower-panels'                    => 'categories#shower_panels'
  get '/steam-solutions.html'             => redirect('/steam-solutions')
  get '/steam-solutions'                  => 'categories#steam_solutions'
  get '/swr-pipes-and-fittings.html'      => redirect('/swr-pipes-and-fittings')
  get '/swr-pipes-and-fittings'           => 'categories#swr_pipes_and_fittings'
  get '/tiles.html'                       => redirect('/tiles')
  get '/tiles'                            => 'categories#tiles'
  get '/upvc-pipes-and-fittings.html'     => redirect('/upvc-pipes-and-fittings')
  get '/upvc-pipes-and-fittings'          => 'categories#upvc_pipes_and_fittings'
  get '/water-heater.html'                => redirect('/water-heater')
  get '/water-heater'                     => 'categories#water_heater'
  get '/water-tank.html'                  => redirect('/water-tank')
  get '/water-tank'                       => 'categories#water_tank'
  get '/contact.html'                     => redirect('/contact')
  post '/contact'                         => 'categories#contact'

  get '/login'                            => 'sessions#new', :as => 'login_path'
  post '/login'                           => 'sessions#create'
  delete '/logout'                        => 'sessions#destroy'

  # resources :users, :only =>[:new,:create,:index]
  get '/users/new'                        => 'users#new', :as => 'signup_path'
  post '/users/create'                    => 'users#create'
  get '/users'                            => 'users#index'
  get '/users/:id'                        => 'users#show', :as => 'user'

  get '/reports'                          => 'reports#index', :as => 'reports'
  get '/reports/new'                      => 'reports#new', :as => 'generate_report'
  post '/reports/create'                  => 'reports#create'
  get '/reports/show'                     => 'reports#show'
  get '/reports/:id'                      => 'reports#show', :as => 'report'
  delete '/reports/:id'                   => 'reports#destroy'
end

app/models/report.rb
class Report < ApplicationRecord
	validates_uniqueness_of :report_code
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
	layout 'report.html.erb'
	before_filter :login_check

	def index
		@reports = Report.all
	end

	# When editing the form do keep in mind to set the default value
	def new
		if params[:data].present?
			@data = JSON.parse(Base64.decode64(params[:data]))
		end
		render 'new'
	end

	def create
		redirect_to action: show, params: params
	end

	def show
		if params[:id].present?
			@data = JSON.parse(Base64.decode64(Report.find(params[:id]).report_code))
		else
			@data = decode_data
			save_report
		end
		render 'show'
	end

	def destroy
		@report = Report.find(params[:id])
		@report.destroy
		redirect_to reports_url
	end

	private

	def decode_data
		JSON.parse(Base64.decode64(show_params))
	end

	def save_report
		report = Report.new
		report.report_code = params[:data]
		report.quote_no = decode_data["quotation"]
		report.project_site = decode_data["site"]
		report.save
	end

	def show_params
		params.require(:data)
	end

	def login_check
		unless logged_in?
			flash[:alert] = "Please login to authenticate yourself."
			flash[:color]= "valid"
			redirect_to login_path_url
		end
	end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/index.html.erb
<table class="table table-striped table-bordered">
	<caption>List of All Reports You Have Generated</caption>
	<thead class="thead-default">
		<tr>
			<th>Quote No</th>
			<th>Project Site</th>
			<th>Reference</th>
			<th>Company Details</th>
			<th>Edit Report</th>
			<th>Show Report</th>
			<th>Delete Report</th>
		</tr>
	</thead>
	<tbody>
		<% @reports.each do |report| %>
			<% temp = JSON.parse(Base64.decode64(report.report_code)) %>
			<tr>
				<td><%= report.quote_no %></td>
				<td><%= report.project_site %></td>
				<td><%= temp["reference"] %></td>
				<td><%= temp['details'].to_a.join("<br>").html_safe %></td>
				<td><a href="/reports/new?data=<%= report.report_code %>" target="_blank">Edit Report</a></td>
				<td><a href="/reports/show?data=<%= report.report_code %>" target="_blank">Show Report</a></td>
				<td><%= link_to 'Destroy', report_path(report),
					method: :delete,
					data: { confirm: 'Are you sure?' } %></td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/reports/new.html.erb
<!-- Setting default values so that form doesn't break -->
<% @data = @data || {
    'quotation' => '',
    'site' => '',
    'reference' => '',
    'details' => [''],
    'items' => [{'make' => '--'}],
    'terms' => {},
    'show_pandf' => false,
    'pandf' => '',
    'show_tax' => false,
    'tax_value' => '0'
    } %>
<% @page_title = "Report Generation" %>
<div class="Login_Form container">
    <h1>Generate Report</h1>
    <% if flash[:alert] %>
        <div id="alert">
            <%= flash[:alert] %> 
        </div>
    <% end %>
    <form id="quotation-rows">
        <h5>Add Company Details</h5>
        <div>
            <label for="quotation">Quotation/Performa:</label>
            <input type="text" name="quotation" id="quotation" value="<%= @data['quotation'] %>">
        </div>
        <br>
        <div>
            <label for="project_site">Project Site:</label>
            <input type="text" name="project_site" id="project_site" value="<%= @data['site'] %>">
        </div>
        <br>
        <div>
            <label for="reference">Reference:</label>
            <input type="text" name="reference" id="reference" value="<%= @data['reference'] %>">
        </div>
        <br>
        <div id="company_details_wrapper">
            <% @data['details'].each do |x| %>
                <div class="company_details">
                    <input type="text" name="company_name" width="200" placeholder="Company Details" value="<%= x %>"/>
                </div>
            <% end %>
        </div>
        <br>
        <input class="btn btn-default" type="button" id="add-detail" name="add-detail" value="Add Detail" />
        <input class="btn btn-default" type="button" id="remove-detail" name="remove-detail" value="Remove Detail" />
        <table class="table">
            <thead>
                <tr>
                <th>Item Description</th>
                <th>Make</th>
                <th>Quantity</th>
                <th>UOM</th>
                <th>Unit Price</th>
                </tr>
            </thead>
            <tbody id="item-container">
            <% @data['items'].each do |x| %>
                <tr class="item-row">
                    <td>
                        <input type="text" name="comment" placeholder="Item Description" value="<%= x['comment'] %>"/>
                    </td>
                    <td>
                        <input type="text" step="1" name="make" width="1" placeholder="Make" required value="<%= x['make'] %>"/>
                    </td>
                    <td>
                        <input type="number" step="1" name="quantity" width="1" placeholder="Quantity" required value="<%= x['quantity'] %>"/>
                    </td>
                    <td>
                        <select name="unit_measurement" required placeholder="Unit Of Measurement">
                            <%= options_for_select([['Nos','No'],['Box','Box'],['Feet','Feet'],['Kg','Kg'],['Mtr','Mtr'],['Bag','Bag']], x['unit_measurement']) %>
                        </select>
                    </td>
                    <td><input type="number" step="1" name="unit_price" width="1" placeholder="Unit Price" required value="<%= x['unit_price'] %>"/></td>
                </tr>
            <% end %>
            </tbody>
        </table>

        <input class="btn btn-default" type="button" id="add-item" name="add-item" value="Add Item" />
        <input class="btn btn-default" type="button" id="remove-item" name="remove-item" value="Remove Item" />
        <hr>
        <div>
            <label for="show_note">Show Note?</label>
            <input type="checkbox" name="show_note" id="show_note" <%= @data['show_note'] ? 'checked' : '' %>
            <label for="note">Note:</label>
            <input type="text" name="note" id="note" value="<%= @data['note'] %>">
        </div>
        <hr>
        <div>
            <label for="show_pandf">Show P & F?</label>
            <input type="checkbox" name="show_pandf" id="show_pandf" <%= @data['show_pandf'] ? 'checked' : '' %>>
            <label for="pandf">Packing And Forwarding:</label>
            <input type="text" name="pandf" id="pandf" value="<%= @data['pandf'] %>">
        </div>
        <hr>
        <div>
            <label for="show_tax">Show Tax?</label>
            <input type="checkbox" name="show_tax" id="show_tax" <%= @data['show_tax'] ? 'checked' : ''%>>
            <select name="tax_value" id="tax_value" placeholder="Tax Value">
                <%= options_for_select([['0%','0'],['5%','0.05'],['14.5%','0.145']], @data['tax_value']) %>
            </select>
        </div>
        <hr>
        <div>
            <div>
                <label for="price">Prices:</label>
                <input type="text" name="price" id="price"value="<%= @data['terms']['price'] %>">
            </div>
            <div>
                <label for="tax">Taxes:</label>
                <input type="text" name="tax" id="tax"value="<%= @data['terms']['tax'] %>">
            </div>
            <div>
                <label for="delivery">Delivery:</label>
                <input type="text" name="delivery" id="delivery"value="<%= @data['terms']['delivery'] %>">
            </div>
            <div>
                <label for="validity">Validity:</label>
                <input type="text" name="validity" id="validity"value="<%= @data['terms']['validity'] %>">
            </div>
            <div>
                <label for="payment">Payment:</label>
                <input type="text" name="payment" id="payment"value="<%= @data['terms']['payment'] %>">
            </div>
        </div>
        <br>
        <hr>
        <div>
            <label for="is_performa">Is Performa?</label>
            <input type="checkbox" name="is_performa" id="is_performa" <%= @data['is_performa'] ? 'checked' : '' %>
        </div>
        <hr>
        <input type="button" id="create-quotation" name="create-quotation" value="Create Quotation">
    </form>​
</div>

app/views/reports/show.html.erb
<div class="report" style="font-size: 16px;">
  <img src=/assets/surana_head.png alt="Surana Header" style="width:100%;" class="company_logo" itemprop="logo">
  <div>
    <div class="text-center clearfix">
    <% if @data['quotation'].present? %>
      <% if @data['is_performa'].present? %>
        <strong style="text-decoration: underline;"><%= @data['quotation'] %></strong>
      <% else %>
        <strong style="text-decoration: underline;">Quotation</strong><strong>: <%= @data['quotation'] %></strong>
      <% end %>
    <% end %>
    <span style="float: right;">Date: <%= Time.now.strftime("%d/%m/%y") %></span></div>
    <% if @data['details'] && @data['details'].length > 0 %>
        <% if @data['is_performa'].present? %>
          <h5>
            M/S,
          </h5>
        <% else %>
          <h4>
            To,
          </h4>
        <% end %>
      </h4>
      <% @data['details'].each do |x| %>
        <h5 style="margin: 2px 0; font-size: 16px;">
          &nbsp;<%= x %>
        </h5>
      <% end %>
    <% end %>
    <% if @data['site'].present? %>
      <h5 style="margin: 2px 0; font-size: 16px;">
        <span style="text-decoration: underline;">Project Site:</span> <%= @data['site'] %>
      </h5>
    <% end %>
    <br>
    <% if @data['is_performa'].present? %>
    <% else %>
      <div>Dear Sir,</div>
      <% if @data['reference'].present? %>
        <div style="font-size: 16px; margin: 0 70px 10px;"><strong style="text-decoration: underline;">Reference:</strong><span>  <%= @data['reference'] %></span></div>
      <% end %>
      <div style="margin-left:30px">We are pleased to quote as below:</div>
      <br>
    <% end %>
    <% if @data['items'] && @data['items'].length > 0 %>
      <table class="table table-bordered table-striped table-condensed">
        <thead>
          <tr>
            <th style="text-align:center;text-decoration:underline;">S.No</th>
            <th style="text-align:center;text-decoration:underline;width: 45%;" id="item">Item Description</th>
            <th style="text-align:center;text-decoration:underline;">Make</th>
            <th style="text-align:center;text-decoration:underline;">Qty</th>
            <th style="text-align:center;text-decoration:underline;">UOM</th>
            <th style="text-align:center;text-decoration:underline;">Unit Price</th>
            <th style="text-align:center;text-decoration:underline;">Total</th>
          </tr>
        </thead>
        <tbody>
          <% grand_total = 0 %>
          <% final_v1 = 0 %>
          <% total = 0 %>
          <% @data['items'].each_with_index do |k,v| %>
            <% total = k['quantity'].to_i*k['unit_price'].to_i %>
            <% grand_total = grand_total + total %>
            <% final_v1 = grand_total %>
            <tr>
              <td class="text-center"><%= v.to_i + 1 %> )</td>
              <td><%= k['comment'] %></td>
              <td class="text-center"><%= k['make'] %></td>
              <td class="text-center"><%= k['quantity'] %></td>
              <td class="text-center"><%= k['unit_measurement'] %></td>
              <td class="text-center"><%= k['unit_price'] %></td>
              <td class="text-center"><%= total.to_s.gsub(/(\d+?)(?=(\d\d)+(\d)(?!\d))(\.\d+)?/, "\\1,") %></td>
            </tr>
          <% end %>
          <% if @data['show_pandf'].present? || @data['show_tax'].present? %>
            <tr>
              <td class="text-right" colspan="6"><strong>Total</strong></td>
              <td class="text-center"><strong><%= grand_total.to_s.gsub(/(\d+?)(?=(\d\d)+(\d)(?!\d))(\.\d+)?/, "\\1,") %></strong></td>
            </tr>
            <% if @data['show_tax'].present? %>
              <tr>
                <td class="text-right" colspan="6"><strong>Taxes</strong></td>
                <td class="text-center"><strong><%= (grand_total*@data['tax_value'].to_f).round.to_s.gsub(/(\d+?)(?=(\d\d)+(\d)(?!\d))(\.\d+)?/, "\\1,") %></strong></td>
              </tr>
            <% end %>
            <% if @data['show_pandf'].present? %>
              <tr>
                <td class="text-right" colspan="6"><strong>Packing And Forwarding:</strong></td>
                <td class="text-center"><strong><%= @data['pandf'].to_i.to_s.gsub(/(\d+?)(?=(\d\d)+(\d)(?!\d))(\.\d+)?/, "\\1,") %></strong></td>
              </tr>
            <% end %>
            <% final_v1 = @data['show_tax'].present? ? (grand_total + (grand_total*@data['tax_value'].to_f).round) : grand_total %>
            <% final_v1 += @data['show_pandf'].present? ? @data['pandf'].to_i : 0 %>
            <tr>
              <td class="text-right" colspan="6"><strong>Grand Total</strong></td>
              <td class="text-center"><strong><%= final_v1.to_s.gsub(/(\d+?)(?=(\d\d)+(\d)(?!\d))(\.\d+)?/, "\\1,") %></strong></td>
            </tr>
          <% else %>
            <tr>
              <td class="text-right" colspan="6"><strong>Grand Total</strong></td>
              <td class="text-center"><strong><%= grand_total.to_s.gsub(/(\d+?)(?=(\d\d)+(\d)(?!\d))(\.\d+)?/, "\\1,") %></strong></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
    <div><strong style="text-decoration: underline;">Amount In Words</strong>: <%= final_v1.to_i.to_words.humanize %> only.</div>
    <% if @data['show_note'].present? %>
      <div><strong style="text-decoration: underline;">Note:</strong> <%= @data['note'] %></div>
    <% end %>
    <br>
    <div><strong style="text-decoration: underline;">Terms and Conditions</strong><strong>:</strong></div>
    <ol style="padding-left: 20px;">
      <% if @data['terms']['price'].present? %>
        <li style="list-style-type: disc;"><strong>Prices:-</strong> <%= @data['terms']['price'] %></li>
      <% end %>
      <% if @data['terms']['tax'].present? %>
        <li style="list-style-type: disc;"><strong>Taxes:-</strong> <%= @data['terms']['tax'] %></li>
      <% end %>
      <% if @data['terms']['delivery'].present? %>
        <li style="list-style-type: disc;"><strong>Delivery:-</strong> <%= @data['terms']['delivery'] %></li>
      <% end %>
      <% if @data['terms']['validity'].present? %>
        <li style="list-style-type: disc;"><strong>Validity:-</strong> <%= @data['terms']['validity'] %></li>
      <% end %>
      <% if @data['terms']['payment'].present? %>
        <li style="list-style-type: disc;"><strong>Payment:-</strong> <%= @data['terms']['payment'] %></li>
      <% end %>
    </ol>
    <div class="text-right">Yours Faithfully,</div>
    <div class="text-right">Gaurav Surana</div>
    <div class="text-right">+91-9849156450</div>
    <br>
    <div class="text-center">
      <h5 class="divFooter">
      This is a system generated 
      <%= @data['is_performa'].present? ? 'performa' : 'quotation' %>, no signature is required.
      </h5>
    </div>
  </div>
</div>